### ISSUE TITLE
string not matched

### ISSUE THREAD

**Issue by bpieck** [sds/haml-lint#324]
Hi,

The following is no need to act on. I just present an issue I ran into - and a suggestion you could add, if less experienced developers run into something similar.

I just installed haml-lint and ran the command line tool. It ends up with following stacktrace:

````
$ haml-lint app/views/
warning: parser/current is loading parser/ruby25, which recognizes
warning: 2.5.7-compliant syntax, but you are running 2.5.8.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
string not matched
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration.rb:120:in `[]='
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration.rb:120:in `block (2 levels) in ensure_linter_include_exclude_arrays_exist'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration.rb:118:in `each'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration.rb:118:in `block in ensure_linter_include_exclude_arrays_exist'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration.rb:117:in `each_key'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration.rb:117:in `ensure_linter_include_exclude_arrays_exist'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration.rb:100:in `validate'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration.rb:21:in `initialize'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration_loader.rb:94:in `new'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration_loader.rb:94:in `load_from_file'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration_loader.rb:54:in `load_file'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/configuration_loader.rb:24:in `load_applicable_config'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/runner.rb:70:in `load_applicable_config'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/runner.rb:20:in `run'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/cli.rb:108:in `scan_for_lints'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/cli.rb:53:in `act_on_options'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/lib/haml_lint/cli.rb:25:in `run'
/home/pieck/.gem/ruby/2.5.8/gems/haml_lint-0.35.0/bin/haml-lint:8:in `<top (required)>'
/home/pieck/.gem/ruby/2.5.8/bin/haml-lint:23:in `load'
/home/pieck/.gem/ruby/2.5.8/bin/haml-lint:23:in `<main>'
Report this bug at https://github.com/sds/haml-lint/issues

To help fix this issue, please include:
- The above stack trace
- Haml-Lint version: 0.35.0
- Haml version: 5.1.2
- RuboCop version: 0.79.0
- Ruby version: 2.5.8
````
Since the issue seems to be somewhere inside configuration, I checked for a config_file - and found one. So someone before me already introuduced haml-lint (2018-04-03) - and just removed it later again (yeah, the project, I took over - has some history ^^):
````
$ cat .haml-lint.yml 
linters:
  LineLength:
    enabled: false
  SpaceInsideHashAttributes: no_space
````
With binding.pry I could figure, that the configuration SpaceInsideHashAttributes just seems to have changed. I removed the file and everything was great again.

I just think, the error here is misleading. So maybe you want to introduce a little helpful error message, when configuration is parsed and was not formatted as expected. If you think so, too - I can do some pull request :)

**Comment by sds** [comment]
Thank you for the feedback. Agreed, the error messages when there is invalid configuration are not helpful.

Would welcome a pull request making this situation more helpful/friendlier. For now, I will close this issue as informational. Appreciate the feedback!
