### ISSUE TITLE
The `--parallel` option sometimes causes `no _dump_data is defined for class Proc (TypeError)`

### ISSUE THREAD

**Issue by radomirbosak** [sds/haml-lint#345]
For certain input file, haml-lint fails with the 
```
.../parallel.rb:494:in `dump': no _dump_data is defined for class Proc (TypeError)
```
error message when `--parallel` option on. Program succeeds without `--parallel` option.

Unfortunately, I don't have access to the file that caused this error, and have only stack trace. I was hoping someone could figure out the error even without the reproducing file.

This is the program output. I see that there are multiple issues, but the one fatal seems the be bottom-most TypeError. 
(the `compatibility-with-ruby-mri` warning happens even without `--parallel`, so it probably has no relation to this)
```console
$ bundle exec haml-lint --reporter json --parallel app/views/**/*.haml

marshal data too short
/home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:84:in `load'
/home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:84:in `work'
/home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:411:in `block (4 levels) in work_in_processes'
/home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:527:in `with_instrumentation'
/home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:410:in `block (3 levels) in work_in_processes'
/home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:398:in `loop'
/home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:398:in `block (2 levels) in work_in_processes'
/home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:222:in `block (4 levels) in in_threads'
Report this bug at https://github.com/sds/haml-lint/issues

To help fix this issue, please include:
- The above stack trace
- Haml-Lint version: 0.37.1
- Haml version: 5.2.2
- RuboCop version: 1.25.0
- Ruby version: 2.7.4

warning: parser/current is loading parser/ruby27, which recognizes2.7.5-compliant syntax, but you are running 2.7.4.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:494:in `dump': no _dump_data is defined for class Proc (TypeError)
	from /home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:494:in `process_incoming_jobs'
	from /home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:465:in `block in worker'
	from /home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'
	from /home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'
	from /home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:447:in `block in create_workers'
	from /home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:446:in `each'
	from /home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:446:in `each_with_index'
	from /home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:446:in `create_workers'
	from /home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:386:in `work_in_processes'
	from /home/analyzer_runner/ruby/gems/parallel-1.21.0/lib/parallel.rb:289:in `map'
	from /home/analyzer_runner/ruby/gems/haml_lint-0.37.1/lib/haml_lint/runner.rb:149:in `warm_cache'
	from /home/analyzer_runner/ruby/gems/haml_lint-0.37.1/lib/haml_lint/runner.rb:140:in `report'
	from /home/analyzer_runner/ruby/gems/haml_lint-0.37.1/lib/haml_lint/runner.rb:28:in `run'
	from /home/analyzer_runner/ruby/gems/haml_lint-0.37.1/lib/haml_lint/cli.rb:108:in `scan_for_lints'
	from /home/analyzer_runner/ruby/gems/haml_lint-0.37.1/lib/haml_lint/cli.rb:53:in `act_on_options'
	from /home/analyzer_runner/ruby/gems/haml_lint-0.37.1/lib/haml_lint/cli.rb:25:in `run'
	from /home/analyzer_runner/ruby/gems/haml_lint-0.37.1/bin/haml-lint:8:in `<top (required)>'
	from /home/analyzer_runner/ruby/bin/haml-lint:25:in `load'
	from /home/analyzer_runner/ruby/bin/haml-lint:25:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:478:in `exec'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
	from /home/analyzer_runner/ruby/bin/bundle:23:in `load'
	from /home/analyzer_runner/ruby/bin/bundle:23:in `<main>'
exit status: 70
```

**Comment by radomirbosak** [comment]
By looking at the code, the stack trace appears to leave the `haml-lint` code in the `warm_cache` function of `runner.rb` and continues to `parallel` dependency:
https://github.com/sds/haml-lint/blob/78a551cd1ae239b8c6ac8686d8f219571c62ac66/lib/haml_lint/runner.rb#L148-L154

I tried searching a bit and [found out](https://stackoverflow.com/a/28747347) that a possible reason for this type of error could be that data inside `Parallel.map` is serialized, which is however impossible for type `Proc` (blocks). 

Is it possible that the `file` or `lints` variables contain a `Proc` object somewhere inside of them?

**Comment by sds** [comment]
I vaguely recall seeing this a few years ago. The primary trigger was the size of the result set being serialized. For example, if you have a _lot_ of lints, I think it's possible for `parallel` to not be able to serialize them correctly so that they can be shared between processes.

A potential fix would be to use a different form of IPC—perhaps serializing the results from each worker to a file and then aggregating those results in the parent process. I don't know what `parallel` recommends in this situation, but if you are sufficiently interested, happy to merge a PR that addresses this issue!

**Comment by sandydn** [comment]
Hello there!
I have the same problem, it is indeed quite random. 
Here are the current versions in my project:
- `Haml: 6.0.5`
- `RuboCop : 1.36.0`
- `Ruby : 3.1.2`
I tried to see if the problem would be solved by changing the version of `Haml-lint` from `0.40.0` => `0.42.0` but I still have the problem. 
Is there an update on this problem?
