### ISSUE TITLE
NoMethodError when running haml lint on file

### ISSUE THREAD

**Issue by mockdeep** [sds/haml-lint#408]
With version 0.46.0 we're seeing a `NoMethodError` on a particular file:

```
$ haml-lint -d app/views/admin/campaigns/_copy_route.html.haml
app/views/admin/campaigns/_copy_route.html.haml:0 [E] RuboCop: Couldn't process the file for linting. NoMethodError: undefined method `[]' for nil:NilClass(DEBUG: Backtrace follows)
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:429:in `raw_ruby_lines_from_haml'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:242:in `visit_tag_attributes'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:201:in `visit_tag'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:42:in `safe_send'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:21:in `visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `block in visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `each'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:16:in `block in visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:205:in `visit_tag'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:42:in `safe_send'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:21:in `visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `block in visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `each'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:16:in `block in visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:163:in `finish_visit_any_script'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:142:in `visit_silent_script'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:42:in `safe_send'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:21:in `visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `block in visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `each'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:16:in `block in visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:205:in `visit_tag'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:42:in `safe_send'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:21:in `visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `block in visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `each'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:16:in `block in visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:205:in `visit_tag'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:42:in `safe_send'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:21:in `visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `block in visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `each'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:16:in `block in visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:163:in `finish_visit_any_script'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:129:in `visit_script'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:42:in `safe_send'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:21:in `visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `block in visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `each'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:32:in `visit_children'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:16:in `block in visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:30:in `visit_root'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:42:in `safe_send'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:21:in `visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/chunk_extractor.rb:25:in `extract'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/ruby_extraction/coordinator.rb:49:in `extract_ruby_source'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/linter/rubocop.rb:65:in `visit_root'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:42:in `safe_send'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/haml_visitor.rb:21:in `visit'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/linter.rb:66:in `run_or_raise'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/linter.rb:28:in `run'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/runner.rb:102:in `block in collect_lints'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/runner.rb:101:in `map'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/runner.rb:101:in `collect_lints'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/runner.rb:159:in `process_file'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/runner.rb:148:in `block in process_files'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/runner.rb:147:in `each'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/runner.rb:147:in `process_files'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/runner.rb:173:in `report'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/runner.rb:30:in `run'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/cli.rb:113:in `scan_for_lints'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/cli.rb:58:in `act_on_options'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/lib/haml_lint/cli.rb:25:in `run'
/home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/haml_lint-0.46.0/bin/haml-lint:8:in `<top (required)>'
/home/fletch/.asdf/installs/ruby/3.2.2/bin/haml-lint:25:in `load'
/home/fletch/.asdf/installs/ruby/3.2.2/bin/haml-lint:25:in `<main>'
/home/fletch/.asdf/installs/ruby/3.2.2/bin/ruby_executable_hooks:22:in `eval'
/home/fletch/.asdf/installs/ruby/3.2.2/bin/ruby_executable_hooks:22:in `<main>'
------

1 file inspected, 1 lint detected
```

<details>
<summary>Here are the full file contents:</summary>

```haml
= form_with(url: admin_campaign_copy_steps_path(campaign), class: 'route-copier form-horizontal') do
  = hidden_field_tag 'id', campaign.id
  .form-group
    = label_tag 'to_campaign', nil, class: 'col-sm-2 control-label'
    .col-sm-5
      = text_field_tag 'to_campaign_id', nil, placeholder: 'campaign id', class: 'form-control'
    .col-sm-3
      = check_box_tag 'with_recipients', true, false
      With recipients
    .col-sm-2
      - if campaign.route_can_be_copied?
        - copy_route_attrs = { class: 'btn btn-primary pull-right', type: 'button', data: { a11y_dialog_show: 'route-copier-confirm' } }
        = button_tag 'Copy route', copy_route_attrs
      - else
        .text-danger.small.bg-info.text-center
          Cannot copy route
          %a.ik12-tooltip{ data: { container: 'body', placement: 'right' },
            title: 'There are a a few situations that can cause this: The route    |
            needs a step (new doc or draft), or  some fields have lost their step. |
            Opening and saving the doc may help, or the route may need attention.  |
            If neither of those is the case, please contact support' }
            More Info
    - aria = { hidden: 'true', labelledby: 'route-copier-confirm-title' }
    .dialog--container#route-copier-confirm{ data: { a11y_dialog: 'route-copier-confirm' }, aria: }
      = dialog_overlay
      .wb-modal
        = close_dialog_button(turbo: false)
        .wb-modal--header#route-copier-confirm-title
          = heading(:h2, :medium, :colored) { 'Confirm Route Copy' }
        .wb-modal--body.wb-text.wb-text--muted
          %p
            Are you sure you want to copy the steps from this campaign to
            %b#to-campaign-title
            %span#copy-with-recipients with recipients
            ?
        .wb-modal--footer
          = component('Button', :primary, type: :submit, data: { disable_with: 'Copying...' }) { 'Yes, copy' }
          = cancel_dialog_button(turbo: false)
```
</details>

**Comment by MaxLap** [comment]
The problem is related to using | for multiline code... This is a complex subject and for now is not supported. I made #410 to avoid failing on this kind of code. It will just be skipped (sorry).

For now, we support multiline code when each line (expect the last) ends with a comma. If you want to try your hand at a PR to improve that, you are welcome to do so.

I don't have a workaround to propose in the meantime, sorry.

**Comment by jaredmoody** [comment]
This is problematic especially when working with stimulus.js which sometimes requires long attribute names; commas are not a valid option for breaking up long string attributes.

**Comment by MaxLap** [comment]
Still working on it. I think I got something for the attributes.

Could you try using this in your Gemfile?

```
gem 'haml_lint', github: "maxlap/haml-lint", ref: '8dc7e6c272fb7bdc7e1746845d2521d0d5649a1b', require: false
```

This doesn't have many tests yet, so there may be bugs, if so, please provide examples that cause the issues. Any feedback is helpful.

Still working on the other cases. (the `-` and `=` scripts)

**Comment by MaxLap** [comment]
Haml-Lint 0.47.0 has been release which fixes this. This can be closed

**Comment by jaredmoody** [comment]
0.47.0 works for me, thanks! 🎉
